<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "catalogue_ftcbtclc"
 *
 * Auto generated by Extension Builder 2021-06-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Catalogue ftcbtclc',
    'description' => 'Un catalogue de produits',
    'category' => 'plugin',
    'author' => 'Theo Chauvreau, Florian Tourinel, Corentyn Boutant, Loic Coissard',
    'author_email' => 'theo.chauvreau@etu.u-bordeaux.fr, florian.tourinel@etu.u-bordeaux.fr, corentyn.boutant@etu.u-bordeaux.fr, loic.coissard@etu.u-bordeaux.fr',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
